version: 2

jobs:

  build:
    working_directory: ~/pyfma
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update
      - run: apt-get install -y pandoc python3-pip
      - run: pip3 install -U pytest pytest-cov pylint pybind11
      - checkout
      # lint
      - run: pylint setup.py test/*.py
      # make sure that rst converts correctly
      - run: pip3 install docutils pygments
      - run: make README.rst
      # install
      - run: pip3 install .
      # The actual test
      - run: cd test/ && pytest
